[Circuit_Version]
RLN_Version = 2
RLN_Type = "rln"

[Circuit_Build]
Circom_Version = "circom compiler 2.1.0"
GitHub_URL = "https://github.com/Rate-Limiting-Nullifier/circom-rln.git"
Git_Commit = "17f0fed"
Compilation_Time = 1768370033

[Files]
Wasm = "circuit.wasm"
Wasm_SHA256SUM = "1ea750d589bbc5020f1b5c895f1a41eeb9cc4138837d0e45d2ccbc5634c1b98e"
Zkey = "final.zkey"
Zkey_SHA256SUM = "df89336297ffb604c44220d215ff54b38c98727752080de2f183a2612fb0a518"
Verification_Key = "verification_key.json"
Verification_Key_SHA256SUM = "641f20a8442e4b5a404a508b3aa9110915139f7ae4c91d6222b4e2f38e71f46a"
