[Circuit_Version]
RLN_Version = 2
RLN_Type = "rln"

[Circuit_Build]
Circom_Version = "circom compiler 2.1.0"
GitHub_URL = "https://github.com/Rate-Limiting-Nullifier/circom-rln.git"
Git_Commit = "17f0fed"
Compilation_Time = 1768370223

[Files]
Wasm = "circuit.wasm"
Wasm_SHA256SUM = "0832dbbf80cc9e43f175ce395d096c2f333ed88575c47373612a88901e69eab2"
Zkey = "final.zkey"
Zkey_SHA256SUM = "c08628988210b314c2747b133d2ad86414dd607bf0262a499002cb2bfdb88be3"
Verification_Key = "verification_key.json"
Verification_Key_SHA256SUM = "b99ea275915d47431eaa365fcf126f40a737aa167237be20bf2e47f8678035b5"
