[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test", "--release", "--", "--nocapture"]

[tasks.test_stateless]
command = "cargo"
args = [
	"test",
	"--release",
	"--no-default-features",
	"--features",
	"stateless",
	"--",
	"--nocapture",
]

[tasks.test_multi_message_id]
command = "cargo"
args = [
	"test",
	"--release",
	"--features",
	"multi-message-id",
	"--",
	"--nocapture",
]

[tasks.bench]
command = "cargo"
args = ["bench"]
